// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-auth-button-signin'
  | 'pref-auth-button-signout'
  | 'pref-auth-status'
  | 'pref-clear-sync'
  | 'pref-help'
  | 'pref-sync-stats'
  | 'pref-title'
  | 'prefs-table-detail'
  | 'prefs-table-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish'
  | 'sync-button-label'
  | 'sync-button-tooltip';
